//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnvioLauncherTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%1")]
        public string FileNameParameter {
            get {
                return ((string)(this["FileNameParameter"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<Processor xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <ExecutablePath>C:\WINDOWS\system32\notepad.exe</ExecutablePath>
  <OptionalParameter>/A</OptionalParameter>
</Processor>")]
        public global::AnvioLauncherTest.Entities.Processors.Processor CurrentProcessor {
            get {
                return ((global::AnvioLauncherTest.Entities.Processors.Processor)(this["CurrentProcessor"]));
            }
            set {
                this["CurrentProcessor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUpgradeRequired {
            get {
                return ((bool)(this["IsUpgradeRequired"]));
            }
            set {
                this["IsUpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<ArrayOfWidgetItem xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs" +
            "d=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::AnvioLauncherTest.Entities.Widgets.WidgetItemCollection WidgetItemCollection {
            get {
                return ((global::AnvioLauncherTest.Entities.Widgets.WidgetItemCollection)(this["WidgetItemCollection"]));
            }
            set {
                this["WidgetItemCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InitialFileSelectionDialogDirectory {
            get {
                return ((string)(this["InitialFileSelectionDialogDirectory"]));
            }
            set {
                this["InitialFileSelectionDialogDirectory"] = value;
            }
        }
    }
}
